dir: "{{.InterfaceDirRelative}}"
inpackage: true
issue-845-fix: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "mock{{.InterfaceName | camelcase}}"
mock-build-tags: "!release"
disable-version-string: true
packages:
  github.com/gemyago/aws-messaging-boilerplate-go/internal/queues:
    interfaces:
      messagePoller:
  github.com/gemyago/aws-messaging-boilerplate-go/internal/api/http/v1controllers:
    interfaces:
      dummyMessagesCommands:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'internal/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler