// Code generated by mockery. DO NOT EDIT.

//go:build !release

package v1controllers

import (
	context "context"

	handlers "github.com/gemyago/aws-sqs-boilerplate-go/internal/api/http/v1routes/handlers"
	mock "github.com/stretchr/testify/mock"

	models "github.com/gemyago/aws-sqs-boilerplate-go/internal/api/http/v1routes/models"
)

// mockDummyMessagesCommands is an autogenerated mock type for the dummyMessagesCommands type
type mockDummyMessagesCommands struct {
	mock.Mock
}

type mockDummyMessagesCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDummyMessagesCommands) EXPECT() *mockDummyMessagesCommands_Expecter {
	return &mockDummyMessagesCommands_Expecter{mock: &_m.Mock}
}

// ProcessMessage provides a mock function with given fields: _a0, _a1
func (_m *mockDummyMessagesCommands) ProcessMessage(_a0 context.Context, _a1 *models.DummyMessage) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.DummyMessage) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDummyMessagesCommands_ProcessMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMessage'
type mockDummyMessagesCommands_ProcessMessage_Call struct {
	*mock.Call
}

// ProcessMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.DummyMessage
func (_e *mockDummyMessagesCommands_Expecter) ProcessMessage(_a0 interface{}, _a1 interface{}) *mockDummyMessagesCommands_ProcessMessage_Call {
	return &mockDummyMessagesCommands_ProcessMessage_Call{Call: _e.mock.On("ProcessMessage", _a0, _a1)}
}

func (_c *mockDummyMessagesCommands_ProcessMessage_Call) Run(run func(_a0 context.Context, _a1 *models.DummyMessage)) *mockDummyMessagesCommands_ProcessMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.DummyMessage))
	})
	return _c
}

func (_c *mockDummyMessagesCommands_ProcessMessage_Call) Return(_a0 error) *mockDummyMessagesCommands_ProcessMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDummyMessagesCommands_ProcessMessage_Call) RunAndReturn(run func(context.Context, *models.DummyMessage) error) *mockDummyMessagesCommands_ProcessMessage_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessage provides a mock function with given fields: _a0, _a1
func (_m *mockDummyMessagesCommands) PublishMessage(_a0 context.Context, _a1 *handlers.MessagesPublishDummyMessageRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *handlers.MessagesPublishDummyMessageRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDummyMessagesCommands_PublishMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessage'
type mockDummyMessagesCommands_PublishMessage_Call struct {
	*mock.Call
}

// PublishMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *handlers.MessagesPublishDummyMessageRequest
func (_e *mockDummyMessagesCommands_Expecter) PublishMessage(_a0 interface{}, _a1 interface{}) *mockDummyMessagesCommands_PublishMessage_Call {
	return &mockDummyMessagesCommands_PublishMessage_Call{Call: _e.mock.On("PublishMessage", _a0, _a1)}
}

func (_c *mockDummyMessagesCommands_PublishMessage_Call) Run(run func(_a0 context.Context, _a1 *handlers.MessagesPublishDummyMessageRequest)) *mockDummyMessagesCommands_PublishMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*handlers.MessagesPublishDummyMessageRequest))
	})
	return _c
}

func (_c *mockDummyMessagesCommands_PublishMessage_Call) Return(_a0 error) *mockDummyMessagesCommands_PublishMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDummyMessagesCommands_PublishMessage_Call) RunAndReturn(run func(context.Context, *handlers.MessagesPublishDummyMessageRequest) error) *mockDummyMessagesCommands_PublishMessage_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDummyMessagesCommands creates a new instance of mockDummyMessagesCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDummyMessagesCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDummyMessagesCommands {
	mock := &mockDummyMessagesCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
