openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example API to publish and consume messages using AWS messaging services
  description: |
    The definition includes API endpoint to publish a message and consume 
    the message from AWS SQS routed via EventBridge.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
paths:
  /messages/publish:
    post:
      summary: Publish a message to the queue
      operationId: publishMessage
      tags:
        - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '202':
          description: Request succeeded
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Message:
      type: object
      description: Simple message object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        comments:
          type: string
    Error:
      type: object
      required:
        - code
      properties:
        code:
          format: string
        message:
          type: string