// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// DummyMessage - Simple message object
type DummyMessage struct { 
	Message string `json:"message"`
	// If true, the message processing will fail. Use this to test error handling, retries and DLQ. 
	FailProcessing bool `json:"failProcessing,omitempty"`
}
